// Глоссарий: подсказки к терминам в уроках (мышь, касание, клавиатура) и страница глоссария (поиск, якорь). Снимки — shots/glossary-*.png.
const path = require('path');
const { launch, sleep } = require('./cdp');
const site = (f) => 'file://' + path.resolve(__dirname, '../site/' + f);
const out = (n) => path.resolve(__dirname, '../shots/' + n);
let bad = 0;
const check = (ok, msg) => { if (!ok) bad++; console.log((ok ? '  ✓ ' : '  ✗ ') + msg); };
(async () => {
  const B = await launch({ w: 1300, h: 900 });
  console.log('Подсказка в уроке 0.3, компьютер');
  let p = await B.page(site('lessons/0-3-kinematika-i-upravlenie.html'), { width: 1280, height: 900, light: true });
  await p.waitFor('document.readyState === "complete"'); await sleep(900);
  const n = await p.eval('document.querySelectorAll(".gl").length');
  check(n >= 8, `терминов с подсказкой: ${n}`);
  await p.eval(`document.querySelector('.gl[data-gl="jacobian"]').scrollIntoView({ block: 'center', behavior: 'instant' }); true`); await sleep(200);
  const r = JSON.parse(await p.eval(`JSON.stringify(document.querySelector('.gl[data-gl="jacobian"]').getBoundingClientRect())`));
  await p.S('Input.dispatchMouseEvent', { type: 'mouseMoved', x: r.x + r.width / 2, y: r.y + r.height / 2 }); await sleep(300);
  const pop = await p.eval('(() => { const e = document.getElementById("glPop"); return e && !e.hidden ? e.textContent : ""; })()');
  check(/Якобиан/.test(pop) && /В глоссарии/.test(pop), 'наведение мышью показывает определение: ' + pop.slice(0, 70));
  const sy = await p.eval('scrollY'); await p.shot(out('glossary-tip-desk.png'), { x: Math.max(0, r.x - 200), y: Math.max(0, r.y + sy - 140), width: 760, height: 360 });
  await p.S('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 5, y: 5 }); await sleep(500);
  check(await p.eval('document.getElementById("glPop").hidden'), 'курсор ушёл — подсказка скрылась');
  check(!p.logs.length, 'консоль урока: ' + (p.logs.join(' | ') || 'чисто'));

  console.log('Подсказка в уроке 1.3, телефон');
  p = await B.page(site('lessons/1-3-multimodalnost-deystviy.html'), { width: 390, height: 844, dpr: 2, mobile: true, light: true });
  await p.waitFor('document.readyState === "complete"'); await sleep(900);
  await p.S('Emulation.setTouchEmulationEnabled', { enabled: true });
  await p.eval(`document.querySelector('.gl[data-gl="cond-mean"]').scrollIntoView({ block: 'center', behavior: 'instant' }); true`); await sleep(200);
  const t = JSON.parse(await p.eval(`JSON.stringify(document.querySelector('.gl[data-gl="cond-mean"]').getBoundingClientRect())`));
  await p.S('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: t.x + t.width / 2, y: t.y + t.height / 2 }] });
  await p.S('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(400);
  const pop2 = await p.eval('(() => { const e = document.getElementById("glPop"); return e && !e.hidden ? e.textContent : ""; })()');
  check(/Условное среднее/.test(pop2), 'касание показывает определение: ' + pop2.slice(0, 60));
  const pr = JSON.parse(await p.eval('JSON.stringify(document.getElementById("glPop").getBoundingClientRect())'));
  check(pr.left >= 0 && pr.right <= 390, `подсказка в пределах экрана: ${Math.round(pr.left)}…${Math.round(pr.right)}`);
  const sy2 = await p.eval('scrollY'); await p.shot(out('glossary-tip-phone.png'), { x: 0, y: Math.max(0, t.y + sy2 - 200), width: 390, height: 560 });
  await p.S('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 20, y: 820 }] });
  await p.S('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(300);
  check(await p.eval('document.getElementById("glPop").hidden'), 'касание мимо закрывает подсказку');
  check((await p.eval('document.documentElement.scrollWidth')) <= 390, 'ширина урока на телефоне в норме');

  console.log('Страница глоссария');
  p = await B.page(site('lessons/glossariy.html#singularity'), { width: 1280, height: 900, light: true });
  await p.waitFor('document.readyState === "complete"'); await sleep(900);
  const total = await p.eval('document.querySelectorAll(".gl-item").length');
  check(total >= 70, `терминов на странице: ${total}`);
  check(await p.eval('document.getElementById("singularity").classList.contains("hit")'), 'якорь #singularity подсвечивает термин');
  await p.eval(`(() => { const q = document.getElementById('glQ'); q.value = 'калман'; q.dispatchEvent(new Event('input')); return true; })()`); await sleep(100);
  const shown = await p.eval('[...document.querySelectorAll(".gl-item")].filter((e) => !e.hidden).map((e) => e.id).join(",")');
  check(/kalman/.test(shown), 'поиск «калман» находит: ' + shown);
  await p.eval(`(() => { const q = document.getElementById('glQ'); q.value = 'attention'; q.dispatchEvent(new Event('input')); return true; })()`); await sleep(100);
  check(/attention/.test(await p.eval('[...document.querySelectorAll(".gl-item")].filter((e) => !e.hidden).map((e) => e.id).join(",")')), 'поиск по английскому названию работает');
  await p.eval(`(() => { const q = document.getElementById('glQ'); q.value = ''; q.dispatchEvent(new Event('input')); window.scrollTo(0, 0); return true; })()`); await sleep(200);
  await p.shot(out('glossary-page.png'), { x: 0, y: 0, width: 1280, height: 1300 });
  const links = JSON.parse(await p.eval('JSON.stringify([...document.querySelectorAll(".gl-from")].map((a) => a.getAttribute("href")))'));
  check(links.every((h) => /^[01]-\d-[a-z-]+\.html#[a-z]/.test(h)), 'у всех терминов ссылка на раздел урока');
  check(!p.logs.length, 'консоль глоссария: ' + (p.logs.join(' | ') || 'чисто'));
  await B.close();
  console.log(bad ? `ИТОГ: ${bad} проверок не прошли` : 'ИТОГ: все проверки прошли');
  process.exit(bad ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
